version: '3'
services:
    web:
        image: homework
        deploy:
            replicas:  5
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G
            restart_policy:
                condition: on-failure
        ports:
            - 8087:8080
        depends_on:
            - mysql
        networks:
            - webnet
            
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        networks:
            - webnet
        environment:
            MYSQL_ROOT_PASSWORD: usbw
            MYSQL_DATABASE: db_docker
            
    adminer:
        image: adminer
        restart: always
        ports:
            - 8089:8080
networks:
    webnet: